### ISSUE TITLE
Adjust Wording to Reflect React and C# Changes

### ISSUE THREAD

**Issue by CalvinPVIII** [epicodus-curriculum/pre-work-full-stack#2]
With React and C# changing places, there are a couple lessons where the pre-work curriculum needs to be updated to reflect that. 

### Getting Started at Epicodus

- [ ] [Independent Projects and Code Reviews](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0j_indepndnt_projects_and_code_reviews.md) lesson, adjust the "Group Work" section to reflect Team Week being at the end of React instead of Intermediate JavaScript.

- [ ] [Final Captsone Project](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0k_final_capstone_project.md) lesson, adjust the breakdown of the capstone schedule to reflect the changes around the React/C# swap.

**Comment by erik-t-irgens** [comment]
Going to add more issues on top of this one, as it's related. 

### [Independent Projects and Code Reviews](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0j_independent_projects_and_code_reviews.md)
- [ ] Adjust Schedule for Full-Time Students, and Schedule for Part-Time students to reflect the addition of a day-time PT cohort.
- [ ]  adjust the "Group Work" section to reflect Team Week being at the end of React instead of Intermediate JavaScript.
- [ ] Update Submission section language to include part-time day language

### [Final Captsone Project](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0k_final_capstone_project.md) lesson
- [ ] adjust the breakdown of the capstone schedule to reflect the changes around the React/C# swap.

### [Curriculum Details: Intro to Programming](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0g_curriculum_details_intro_to_programming.md)
- [ ] In the feedback section, replace the image of the old LHTP UI.

### [Attendance Policy](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0f_remote_attendance_policy.md)
- [ ] Sign-in and Sign-out windows section needs an update to include pt-day language.

### [Internship Coursework and Career Reviews](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0jab_internship_coursework_and_career_reviews.md)
- [ ] Assignment Schedule section: links to FT and PT CS schedules are the same information. do they need to be different information?
- [ ] Review Process & resubmissions section needs updated language for pt-day
- [ ] Final Project Deadlines needs the same language update
- [ ] Uncertain if this page needs further changes due to CS rewrites

### [Career Services Schedule](https://github.com/epicodus-curriculum/career-services-full-stack/blob/main/ft20weeks-career-services-master-schedule.md)
- [ ] Needs a total rewrite based on the CS changes
- [ ] Needs a full-time and a part-time version???

### [Preparing for the First Week](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0i_preparing_for_the_first_week.md)
- [ ] Course Section Objectives section needs updated links for all 4 tracks
- [ ] Daily Expectations section needs updated links, as they shouldn't go to Tuesday Schedule and Expectations, but also need them for all tracks.

### [Daily Schedules for All Students](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0ea_daily_schedule.md)
- [ ] A Typical Class Day section needs updated Part-time language, perhaps just a new section for day-time part-time. 

### [Student Success and Skills](https://github.com/epicodus-curriculum/career-services-full-stack/blob/main/student-success-skills.md)
- [ ] Schedules need to be updated for PT Day

**Comment by erik-t-irgens** [comment]
Closing this issue as it's covered in [this issue here](https://github.com/epicodus-curriculum/pre-work-full-stack/issues/3)
