### ISSUE TITLE
All Pre-work Lesson Rewrite Tasks

### ISSUE THREAD

**Issue by erik-t-irgens** [epicodus-curriculum/pre-work-full-stack#3]
Going to add more issues on top of this one, as it's related. 

### [Independent Projects and Code Reviews](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0j_independent_projects_and_code_reviews.md)
- [x] Adjust Schedule for Full-Time Students, and Schedule for Part-Time students to reflect the addition of a day-time PT cohort.
- [x]  adjust the "Group Work" section to reflect Team Week being at the end of React instead of Intermediate JavaScript.
- [x] Update Submission section language to include part-time day language

### [Final Captsone Project](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0k_final_capstone_project.md) lesson
- [x] adjust the breakdown of the capstone schedule to reflect the changes around the React/C# swap.

### [Curriculum Details: Intro to Programming](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0g_curriculum_details_intro_to_programming.md)
- [x] In the feedback section, replace the image of the old LHTP UI.

### [Attendance Policy](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0f_remote_attendance_policy.md)
- [x] Sign-in and Sign-out windows section needs an update to include pt-day language.

### [Internship Coursework and Career Reviews](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0jab_internship_coursework_and_career_reviews.md)
- [x] Assignment Schedule section: links to FT and PT CS schedules are the same information. do they need to be different information?
- [x] Review Process & resubmissions section needs updated language for pt-day
- [x] Final Project Deadlines needs the same language update
- [x] Uncertain if this page needs further changes due to CS rewrites

### [Career Services Schedule](https://github.com/epicodus-curriculum/career-services-full-stack/blob/main/ft20weeks-career-services-master-schedule.md)
- [x] Needs a total rewrite based on the CS changes
- [x] Needs a full-time and a part-time version???

### [Preparing for the First Week](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0i_preparing_for_the_first_week.md)
- [x] Course Section Objectives section needs updated links for all 4 tracks
- [x] Daily Expectations section needs updated links, as they shouldn't go to Tuesday Schedule and Expectations, but also need them for all tracks.

### [Daily Schedules for All Students](https://github.com/epicodus-curriculum/pre-work-full-stack/blob/main/0ea_daily_schedule.md)
- [x] A Typical Class Day section needs updated Part-time language, perhaps just a new section for day-time part-time. 

### [Student Success and Skills](https://github.com/epicodus-curriculum/career-services-full-stack/blob/main/student-success-skills.md)
- [x] Schedules need to be updated for PT Day

_Originally posted by @erik-t-irgens in https://github.com/epicodus-curriculum/pre-work-full-stack/issues/2#issuecomment-1738257059_

**Comment by charcezanne** [comment]
Internship Coursework and Career Reviews:
Bullet 1: FT and PT CS schedules do need to be different. Both will need to be updated. We have the info to create an FT career services schedule to replace the current version, and PT will still need to be mapped out. 
Bullet 4: This page *may* need further updates. If we make time in class for the pass/fail career reviews during the first couple of weeks, we don't need to change the wording. If we do not make time in class and assign these CRs as homework, we'll need to update the CR wording to say that *most* CRs will have an info session and time in class to complete them. We also need to change the due date wording for PT from Sunday to Monday. 

Career Services Schedule: 
Bullet 2: They will be different once we have PT mapped out (asap) 

Student Success and Skills: 
Bullet 1: This one looks good, with the exception of the PT days schedule. I think we could maybe use the same due date calendar image for both since they are basically aligned now?

**Comment by erik-t-irgens** [comment]
Done!
